# Generated by Django 3.2.7 on 2021-12-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20211230_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
