# Generated by Django 3.2.7 on 2021-12-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20211230_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
