# Generated by Django 3.2.7 on 2021-12-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_conversation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='content',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
