# Generated by Django 3.2.7 on 2021-12-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_auto_20211231_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='sender',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
