# Generated by Django 3.2.7 on 2022-01-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0012_messages_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='slug',
        ),
    ]
