# Generated by Django 3.2.7 on 2022-01-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0013_remove_messages_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
