# Generated by Django 3.2.7 on 2022-01-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0014_conversation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='slug',
        ),
    ]
