# Generated by Django 3.2.7 on 2022-01-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0018_auto_20220102_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='ssen_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
