# Generated by Django 3.2.7 on 2022-01-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0019_auto_20220102_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='decoded',
            field=models.CharField(default='a', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
