# Generated by Django 3.2.7 on 2022-01-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0020_auto_20220102_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='is_seen',
        ),
    ]
