# Generated by Django 3.2.7 on 2022-01-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0022_rename_ssen_time_conversation_seen_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='serializer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='serializer',
            field=models.BooleanField(default=True),
        ),
    ]
