# Generated by Django 3.2.7 on 2021-10-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_img_url', models.CharField(max_length=1000)),
                ('post_content', models.CharField(max_length=50000)),
            ],
        ),
    ]
