# Generated by Django 3.2.7 on 2021-10-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_content',
            field=models.TextField(max_length=50000),
        ),
    ]
