# Generated by Django 3.2.7 on 2021-10-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_posts_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='post_img_url',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='post_title',
            new_name='title',
        ),
    ]
