# Generated by Django 3.2.7 on 2022-01-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_comments_serializer'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_replays',
            name='serializer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filtercomments',
            name='serializer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='serializer',
            field=models.BooleanField(default=True),
        ),
    ]
