# Generated by Django 3.2.7 on 2021-11-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20211024_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
