# Generated by Django 3.2.7 on 2022-01-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20220114_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments_replays',
            old_name='user',
            new_name='replay_user',
        ),
    ]
