# Generated by Django 3.2.7 on 2021-11-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='posttitle',
        ),
    ]
