# Generated by Django 3.2.7 on 2022-01-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_rename_user_comments_replays_replay_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments_replays',
            old_name='replay_user',
            new_name='user',
        ),
    ]
