# Generated by Django 3.2.7 on 2021-11-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_rename_posttitle_comments_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='show_comment',
            field=models.BooleanField(default=False),
        ),
    ]
