# Generated by Django 3.2.7 on 2021-11-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_comments_show_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='show_comments',
            field=models.BooleanField(default=False),
        ),
    ]
