# Generated by Django 3.2.7 on 2021-11-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_comments_show_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='show_comments',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
