# Generated by Django 3.2.7 on 2021-11-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_alter_comments_show_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='show_comment_color',
            field=models.CharField(default='bg-warning', max_length=20),
        ),
        migrations.AddField(
            model_name='comments',
            name='show_comment_label',
            field=models.CharField(default='Not Published', max_length=20),
        ),
        migrations.AlterField(
            model_name='comments',
            name='show_comments',
            field=models.CharField(default='hidden', max_length=10),
        ),
    ]
