# Generated by Django 3.2.7 on 2021-11-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_auto_20211125_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='show_comment_color',
            field=models.CharField(default='red', max_length=20),
        ),
    ]
