# Generated by Django 3.2.7 on 2021-11-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_alter_comments_show_comment_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=' ', max_length=20, null=True)),
            ],
        ),
    ]
