# Generated by Django 3.2.7 on 2021-11-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_alter_posts_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='img',
            new_name='image',
        ),
    ]
