# Generated by Django 3.2.7 on 2021-11-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_comments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
    ]
