# Generated by Django 3.2.7 on 2021-11-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_logs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='logs',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
