# Generated by Django 3.2.7 on 2021-12-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_posts_draft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='posts',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
