# Generated by Django 3.2.7 on 2021-12-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0028_auto_20211203_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='draft_color',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='draft_or_published',
        ),
    ]
