# Generated by Django 3.2.7 on 2021-12-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0029_auto_20211203_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='temporary',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
