# Generated by Django 3.2.7 on 2021-12-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0030_posts_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
