# Generated by Django 3.2.7 on 2021-12-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='has_module_perms',
            field=models.BooleanField(default=False),
        ),
    ]
