# Generated by Django 3.2.7 on 2021-12-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accounts_has_module_perms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='has_module_perms',
        ),
    ]
