# Generated by Django 3.2.7 on 2022-01-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accounts_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='Address',
            field=models.CharField(blank=True, default='Kabul', max_length=200),
        ),
    ]
