# Generated by Django 3.2.7 on 2022-01-16 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_accounts_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='Address',
            new_name='address',
        ),
    ]
